
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\DATTA\.vscode\Tkinter-Designer-master\register\build\generate.png")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("393x852")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 852,
    width = 393,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    100.0,
    103.0,
    390.0,
    373.0,
    fill="#000000",
    outline="")

canvas.create_text(
    101.0,
    255.0,
    anchor="nw",
    text="Welcome Onboard!",
    fill="#000000",
    font=("Poppins SemiBold", 18 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=30.0,
    y=703.0,
    width=325.0,
    height=62.0
)

canvas.create_rectangle(
    45.0,
    403.0,
    370.0,
    454.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    45.0,
    317.0,
    370.0,
    369.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    45.0,
    489.0,
    370.0,
    540.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    45.0,
    574.0,
    370.0,
    626.0,
    fill="#000000",
    outline="")

canvas.create_text(
    58.0,
    806.0,
    anchor="nw",
    text="Already have an account ? Sign In",
    fill="#000000",
    font=("Poppins Regular", 14 * -1)
)
window.resizable(False, False)
window.mainloop()
